# Generated by Django 4.1.3 on 2022-11-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('is_published', models.BooleanField(verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
