# Generated by Django 4.1.3 on 2022-11-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_location_remove_ads_address_ads_category_ads_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='Описание'),
        ),
    ]
