# Generated by Django 4.1.3 on 2022-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ads_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия'),
        ),
    ]
